name: "Unit test vitest project"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - run: npm run biome:ci
        name: Run the Biome checks
      - run: npm run build
        name: Build the project to check for errors
      - run: npm test
        name: Run the unit tests